name: Release

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Setup Git Config
        run: |
          git config --global url."https://github.com/".insteadOf "git:github.com/"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release